### ISSUE TITLE
ModuleNotFoundError: No module named 'nerfstudio.fields.visibility_field'

### ISSUE THREAD

**Issue by jiennyteng** [ethanweber/nerfbusters#1]

**Comment by ethanweber** [comment]
Hi @jiennyteng, you'll need to checkout the [nerfbusters-changes ](https://github.com/nerfstudio-project/nerfstudio/tree/nerfbusters-changes) branch on nerfstudio for this module. You can see our PR for more details at https://github.com/nerfstudio-project/nerfstudio/pull/1786.
