### ISSUE TITLE
the VisibilityField

### ISSUE THREAD

**Issue by pomoron** [ethanweber/nerfbusters#11]
Hi Ethan,

Thanks for your great work on post-cleaning trained nerf results. I have problems when launching the standard `ns-train` routine after installing the nerfbuster repo. Your file in <repo>/nerfbusters/nerfbusters/nerf/nerfbusters_pipeline.py currently imports the visibility field class by:
`from nerfstudio.fields.visibility_field import VisibilityField`

The original nerfstudio package in <repo>/nerfstudio/nerfstudio/fields contains several field calculations for different types of nerf. None of those however contains the class VisibilityField (in fact I can't find one that calculates visibility as a field). Could you please supplement the required files/codes that allow the class to be imported?

Regards,
Pomoron

**Comment by michalilski** [comment]
Also facing the same issue.

**Comment by ethanweber** [comment]
Hey all, you can have a look at this [PR](https://github.com/nerfstudio-project/nerfstudio/pull/2264/files). I don't expect it to be merged into main anytime soon but you can grab the parts of the code that you'd like / feel free to reference any parts of it.
