### ISSUE TITLE
data download path

### ISSUE THREAD

**Issue by jaggzh** [ethanweber/nerfbusters#16]
Hey Ethan! :)
Where's the preferable location for the data/ dir?
At present it seems relative to the local run of `nerfbusters-setup`
(I happen to be in my ~/bin/ right now):

```python
42     def download(self, save_dir: Path):
43         # Download the files
44         url = "https://drive.google.com/uc?id=1iioFQrH8cCmYxjLSoBb6DHHP7pP4QnIp"
45         download_path = str(save_dir / "nerfbusters-diffusion-cube-weights.ckpt")
46         import ipdb; ipdb.set_trace(context=16); pass
---> 47         gdown.download(url, output=download_path)
48
49
50 @dataclass
51 class NerfbustersCapturesDownload(DatasetDownload):
52     """Download the Nerfbusters captures."""
53
54     def download(self, save_dir: Path):

ipdb> download_path
'data/nerfbusters-diffusion-cube-weights.ckpt'
```

**Comment by ethanweber** [comment]
Hey @jaggzh, it should be where the repo is in a folder named `data`.

**Comment by jaggzh** [comment]
With a pip install it ends up just relative to the current path when run.

(Also, it seems you committed some huge files to your repo in the past; I
terminated a clone of the repo after it reached like 1gb or something. I
just had to learn --depth to limit it). You might want to risk a git filter
of the history and I'm suspecting it could get in the way of others trying
to participate (when they fork/clone).
