### ISSUE TITLE
shapenet dataset error

### ISSUE THREAD

**Issue by ssoiy** [ethanweber/nerfbusters#2]
hi, when i train this code, i got this error
 "ValueError : string is not a file: /path/ShapeNetCore.v2/04379243/models/model_normalized.obj"
at "cubes3d.py : 131" trimesh.load function

should i change some format of shapenet?

and Do I need to create a train_labels.txt to train the shapenetcore.v2 dataset?
there's no train_labels.txt in shapenet dataset

thank you

**Comment by ethanweber** [comment]
Hi @ssoiy, I fixed the harded file path in our code. Now you can put the ShapeNetCore.v2 folder (or symlink) in the local data folder, as described in the README.md now [here](https://github.com/ethanweber/nerfbusters#train-3d-diffusion-model).

There are instructions for how to download the shapenet dataset, which you can use the command `wget https://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v2.zip --no-check-certificate` for. Feel free to reopen this issue if your problems persist. Thanks!

**Comment by Harr7y** [comment]
Sorry, I still can not solve this problem, can you give some advices?  

File "/home/nerfbusters/nerfbusters/data_modules/datamodule.py", line 47, in setup
    self.train_dataset = Cubes3D(
  File "/home/nerfbusters/nerfbusters/data_modules/cubes3d.py", line 79, in __init__
    with open(os.path.join(path, "train_labels.txt"), "r") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'data/ShapeNetCore.v2/train_labels.txt'

**Comment by ethanweber** [comment]
Hm, so what is inside your folder `data/ShapeNetCore.v2`? Maybe you need to symlink it to where you installed ShapeNet?

**Comment by Harr7y** [comment]
Thanks for your reply. The data/ShapeNetCore.v2 is the dataset downloaded following the link provided in the nerfbusters.
(https://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v2.zip)

<img width="286" alt="1703599363851" src="https://github.com/ethanweber/nerfbusters/assets/33324651/a771d3be-9441-45d7-9008-3d249a7bd4fa">

According to the code, I think maybe the "train_labels.txt" is missed.

**Comment by ethanweber** [comment]
Hey, hm, I'm not too sure why it's not there. Here I've uploaded a copy of that file for you. Maybe that will help you?

[train_labels.txt](https://github.com/ethanweber/nerfbusters/files/13797086/train_labels.txt)

**Comment by Harr7y** [comment]
Thanks a lot~ :pray::pray:
