### ISSUE TITLE
The link to the pretrained 3D diffusion ckpt is Wrong.

### ISSUE THREAD

**Issue by BooguTeam** [ethanweber/nerfbusters#20]
Thanks for your great work, but I found there is something wrong with the link to the pretrained 3D diffusion checkpoint.

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.

**Comment by Harr7y** [comment]
Following the read.md to train the 3D diffusion model from scratch, an error occurs:
ImportError: cannot import name 'Crop' from partially initialized module 'nerfbusters.cubes.datasets3D' (most likely due to a circular import) (/home/nerfbusters/nerfbusters/cubes/datasets3D.py)

**Comment by ethanweber** [comment]
Hm, this link seems to work for me: [https://drive.google.com/uc?id=1iioFQrH8cCmYxjLSoBb6DHHP7pP4QnIp](https://drive.google.com/uc?id=1iioFQrH8cCmYxjLSoBb6DHHP7pP4QnIp). How about for you?

**Comment by ethanweber** [comment]
EDIT: I just fixed the README.md per this issue, #15! The download script was fine but the README.md was out of date. Thanks!

**Comment by Harr7y** [comment]
It works now! Thanks a lot~
