### ISSUE TITLE
[Visibility median count] Where is the preprocessing code for this ?

### ISSUE THREAD

**Issue by minsu1206** [ethanweber/nerfbusters#25]
Hi

I want to compute visibility median count map for my own scene and mipnerf360 dataset.

<img width="630" alt="image" src="https://github.com/ethanweber/nerfbusters/assets/59243570/b01cef7c-6a7d-4614-9ddc-220767792dbe">

I understand how the process works, but I couldn't find the code for processing this map. I would appreciate it if you could let me know where the code is.

Thanks in advance.

**Comment by ethanweber** [comment]
Hey @minsu1206, maybe you can reference this code for how we did it: https://github.com/nerfstudio-project/nerfstudio/pull/2264/files. Let me know if it's not clear. Thanks for the interest in this part of the method!

**Comment by minsu1206** [comment]
Thanks.

Could you check my rough understanding is correct or not ?

1. Make a set of ray samples which march from camera origin through each pixel coordinate ( let's call this {R} )
2.{R} as input -> VisibilityField.forward( ) -> computed visibility ( # the number of camera frustums that the point belongs to)
3. computed visibility & weights as inputs -> VIsibilityRenderer.forward( ) ( computed_median is used here) -> final result

**Comment by ethanweber** [comment]
My bad for not replying earlier, but yes, I think that sounds correct. The way you describe would be good for visualizing an visibility render in the viewer. If you want to use it as a loss, then I skip rendering it and instead penalize nonzero densities wherever a sample has fewer than N visible cameras.

**Comment by minsu1206** [comment]
Thanks. It helped me a lot !
I'll close this issue.
