### ISSUE TITLE
I can't find the file.['diffusers']

### ISSUE THREAD

**Issue by HkDzl** [ethanweber/nerfbusters#4]
May I ask where the file named diffusers is? thanks

**Comment by ethanweber** [comment]
Hi @HkDzl, the diffusers library should come from the requirements [here](https://github.com/ethanweber/nerfbusters/blob/0a5128e316465bbbbee5769dd3ad9ea1e9a0adee/pyproject.toml#L15). It should install with `pip install -e .`.
