### ISSUE TITLE
Large Depth Error

### ISSUE THREAD

**Issue by codyreading** [ethanweber/nerfbusters#6]
Hi, and thanks for the great work!

I have reproduced the experiments in Table 1, and for the most part the metrics are very similar to reported in the paper. The only inconsistency I found was the Depth metric.

Paper:
![image](https://github.com/ethanweber/nerfbusters/assets/15750604/be62dc4b-9576-40d2-9070-aaf6b992fca8)

Reproduced:
![image](https://github.com/ethanweber/nerfbusters/assets/15750604/4882855a-31f3-4578-89ca-6a975e4e6a9e)

I was wondering if this type of behavior is expected between different runs?

**Comment by ethanweber** [comment]
Hi @codyreading, that's interesting. How do the depth maps look qualitatively? Does that also look incorrect?

**Comment by codyreading** [comment]
Depth Maps look quite good qualitatively, I've uploaded some of the results [here](https://drive.google.com/drive/folders/1h0EzP7T6C433ENTU4Eui9NiLGZDjNixZ?usp=drive_link) of nerfacto-visibility-cube:

If you could upload your depth maps, I'd love to compare them to visually see any differences.

**Comment by ethanweber** [comment]
Hi @codyreading, I requested access to your link. When you compute the metrics, do you clip the depth from 0 to 2? We do that in our evaluation [here](https://github.com/ethanweber/nerfbusters/blob/1f4240344ecff1313f6dfa7be5e06fe7d3e29154/scripts/launch_nerf.py#L194).

**Comment by ethanweber** [comment]
The depth maps you have look correct as far as I can tell. One more thing to double check is that you are using `median` depth instead of `expected` depth when rendering.

**Comment by codyreading** [comment]
Okay let me check these out, thanks!

**Comment by codyreading** [comment]
Hey @ethanweber! Apologies for the delay, but just checked that we clipped the depth from 0-2 and also used `median` depth, I kept all the defaults.

I can rerun this to see if this type of behaviour is reoccuring.

**Comment by codyreading** [comment]
Closing for now, I don't need to reproduce the depth metrics any longer
