### ISSUE TITLE
ModuleNotFoundError: No module named 'nerfstudio.fields.visibility_field'

### ISSUE THREAD

**Issue by selitvin** [ethanweber/nerfbusters#7]
When running nerfbusters (githash 1f4240344ecff1313f6dfa7be5e06fe7d3e29154) with nerfstudio (4d80f0ceeefa13e91e14e9cdebec39232b5cb72e) I get `ModuleNotFoundError: No module named 'nerfstudio.fields.visibility_field'` error. Is there a particular version/githash of nerfstudio that I need?

**Comment by selitvin** [comment]
Oh, sorry. I see it's fixed here: https://github.com/nerfstudio-project/nerfstudio/pull/2264

**Comment by davidceka** [comment]
Hi @selitvin, I'm encountering the same problem: how did you fix it? I followed the link you posted but I didn't quite know what to do
