### ISSUE TITLE
invalid choice: 'nerfbusters'

### ISSUE THREAD

**Issue by vinodrajendran001** [ethanweber/nerfbusters#9]
I've nerfstudio already installed. So I followed from step 3 to install the `nerfbusters` but after executing all the commands  successfully I am getting the below error when I try to use `nerfbusters`
```
$ ns-train nerfbusters --help
```

ns-train: error: argument {nerfacto,depth-nerfacto,instant-ngp,instant-ngp-bounded,mipnerf,semantic-nerfw,vanilla-nerf,tensorf,dnerf,phototourism}: invalid choice: 'nerfbusters' (choose from 'nerfacto', 'depth-nerfacto', 'instant-ngp', 'instant-ngp-bounded', 'mipnerf', 'semantic-nerfw', 'vanilla-nerf', 'tensorf', 'dnerf', 'phototourism')

Am I missing something?

**Comment by ethanweber** [comment]
Hi @vinodrajendran001, it's not as plug-and-play as we'd like at the moment. You'd have to pip install the nerfbusters repo, and it won't work out of the box with the main branch of nerfstudio. However, all the relevant code changes can be found here. https://github.com/nerfstudio-project/nerfstudio/pull/1786
